extends:
  - leankit
  - leankit/es6
  - plugin:import/errors
globals:
  testHelpers: false
parser: babel-eslint
plugins:
  - babel
rules:
  max-nested-callbacks: 0
  init-declarations: 0
  arrow-parens: 0
  no-shadow: 0
  camelcase: 0
  no-magic-numbers: 0
